apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
    app.kubernetes.io/component: dns
type: Opaque
stringData:
  EDGE_HOSTNAME: ENC[AES256_GCM,data:Byf4mpEHB3LBltQFJFSXP3wld3M8RhlMnfOtYu0=,iv:tINxmemnvGbpaphA+M/2dDJ0HYJESfQ5ZQcPY0My//w=,tag:TAHJ0yJfCGRsc+Nwa2zkrw==,type:str]
data:
  EDGE_HOSTNAME: ENC[AES256_GCM,data:Yugg3yXOBNDHB45eQ3cPw7yMqiUCyCnvHkravMAL5hAyKHH1xRDvQA==,iv:TtR9bP4d6oJ3US7LW021e/iW3bGwQVleSZBZS/G9rjc=,tag:qOpragTYl24gMszPMHNLhA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUy9jZmRxTUpzMjdjeHZy
        Tithd2J5TEVsZDRKRjRSbkU5NEZGZlZVckRRCjJyUW1mNDZ0dWpUcHZUZ05nRG11
        MjRxYVo3dy8weWlOZzhWemh5THdta3cKLS0tIDJkMVpUQUdUTFMwcHBQV2JtOVRC
        Q3BhN2pKUzh0NTk0ZFdGUzU4ZzUwVnMKrGpEVnAZ/Qs/1fmEqB3PYzTtpJGWbRQo
        TFsTBaIe+jwE2KollBMgLCzqOrLZlWKthxlFs2SvIqnogUk94RbgUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T18:01:52Z"
  mac: ENC[AES256_GCM,data:dFUATZl7ZTghnMHnfXtQ/XU6ogkDZYNvZP5DOIg7BtvR7vg00XvdXErTmnURGC8mHqxPLqNPuTGz/HsY91VlawR/xcDY1pOjn2yGof6XRmMrnEuPovGBUHkTtJltMt53hglbeuI8KmFfTK43Q3eG2M1Wwd08yxuNUd4WhuE8FMo=,iv:TjfpBN7XaqmBQ8b/nFftbpeivoE3Ru0dIraRWjdZZMg=,tag:nCp6xfFVD+V1QZZTM9ImbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
