apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
    app.kubernetes.io/component: dns
type: Opaque
stringData:
  EDGE_HOSTNAME: ENC[AES256_GCM,data:dFNAU0FJqHA1aVYo8cTl3iHgmQ==,iv:BYzt/cOA6xE+kHlKOW6R9eVwzvW0Sxc30x4aWzmaovM=,tag:YT+tthrxxqIiei5+KKRWgg==,type:str]
data:
  EDGE_HOSTNAME: ENC[AES256_GCM,data:7jC60xGwIpd1T3yQXJIe1qM6MbmJt1OwwOUpWQ==,iv:uRukLYsxex0mBBwl7oGRvl9KCPBjyMTt8ILmCqn4210=,tag:WLF8eevMuR/PjsJrtmAYnA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUy9jZmRxTUpzMjdjeHZy
        Tithd2J5TEVsZDRKRjRSbkU5NEZGZlZVckRRCjJyUW1mNDZ0dWpUcHZUZ05nRG11
        MjRxYVo3dy8weWlOZzhWemh5THdta3cKLS0tIDJkMVpUQUdUTFMwcHBQV2JtOVRC
        Q3BhN2pKUzh0NTk0ZFdGUzU4ZzUwVnMKrGpEVnAZ/Qs/1fmEqB3PYzTtpJGWbRQo
        TFsTBaIe+jwE2KollBMgLCzqOrLZlWKthxlFs2SvIqnogUk94RbgUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T18:35:02Z"
  mac: ENC[AES256_GCM,data:KmyKBiKu3KB1i4OEkRYZnkXbJnBv5OMlfrtJW+1UFfeYpqKLlRiixALrk+gwuEWt34YkaHZRdupKfzvmmG0H+Y3pwleKeE8V8aYwfbhA8+uUg3dpt01skgb3s4XUm7odfbDhNfF1pVre+e3TAfawr5AGzENXa+8VVYVjM+0O6dE=,iv:qUEO5lpfVIWjCr6y/r7QpBNO47BF88GqMGCxgOWdZnY=,tag:J9RS68AyqX/XwqLIqYtSWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
