apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel
  labels:
    app.kubernetes.io/name: beszel
    app.kubernetes.io/instance: beszel-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: beszel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: beszel
    spec:
      containers:
        - name: beszel
          image: henrygd/beszel:0.18.6@sha256:3135185161e072a5058f7c05b247345072bd9f3e23a4a9cd8c879880b085bc41
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          volumeMounts:
            - name: data
              mountPath: /beszel_data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: beszel-data
