apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  labels:
    app.kubernetes.io/name: changedetection
    app.kubernetes.io/instance: changedetection-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: changedetection
  template:
    metadata:
      labels:
        app.kubernetes.io/name: changedetection
    spec:
      containers:
        - name: changedetection
          image: dgtlmoon/changedetection.io:0.54.7@sha256:b632a9fb6be702fb859e02cd5cac5de7a7466ce1e97f5f5347a1d012c0720108
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: BASE_URL
              value: "https://change.romanpeters.nl"
            - name: PLAYWRIGHT_DRIVER_URL
              value: "ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true"
          volumeMounts:
            - name: data
              mountPath: /datastore
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: changedetection-data
