apiVersion: v1
kind: Secret
metadata:
  name: gluetun-wireguard
  namespace: media
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:+5uM/0dRfldaEHkIcsezogUFFPKnT7wDsuMWQf8o07dGHECAZbP4t9P9HL8=,iv:XOiW9OPy7tdnvuiSUgun05ISuM+5escvtb/fZrsQ6kw=,tag:gOngeCyja6MR9Mv9Y0gNhQ==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:7yd5R7FN6kIDqBs=,iv:VhbhJX6O6tZci937zL8mh4hRyx7djWjxUH21YuXvrZ8=,tag:7RmFsnIkKst6p1dYWVE70Q==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:jTKDBvC8iLKLAlszDoa7JmfFBftALnzyUiOG63gKK1skyW89t1i6RjnzX6Q=,iv:X2yPwff9k371iAGICEgxpH7ouJgTyErZOCnMEAGLB64=,tag:h4ikRwzZK+TFXpCi4hahLw==,type:str]
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:I4i3VWNP4lmoeeEQ,iv:t+xUnNx+SIJkp64J6P1bs5FwXxB13rFqf102+YnaG0E=,tag:q6F+9b0jwZPRRhKV1cAAkQ==,type:str]
  WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:qPLII14=,iv:rsJQrinpKvS+pyKjE/eUCHYQ+F2zfebcu6WYR2kxB6Y=,tag:ZkVjw0j4hFhOHSsHTr6ycA==,type:str]
  WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:+iPRRmF71oruItM91XOd,iv:zf2NN8v2Ovay5S/5T9yHcx6vIqESWHB0pkz5OnUhyx8=,tag:xc3OHnvsJQPZK6JqhLb32Q==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIejcyckpaT0E5cHE3SUJo
        VUFURnBoQVpiMXBQYTBuY1dzcmtDUHhwSkNZClMwTlFwczJNcEFVNTJaZTNUc3B6
        eTZhWU1DTTdySW5ySm5hOENUeDV1NkkKLS0tIHUwbDRDOVFLcDFQLzBVUG94amUz
        V0E5SERpR0ZDNGFqcmFMVUdobCtyYm8KuAHVNhrhVhsRBEv8AFTW1RjHnb1gmTC3
        9APMnW2PnaIn75KRuKOpqXhP/qKNZ/umYRI2xUSO36X76+jB6KFoiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T17:47:57Z"
  mac: ENC[AES256_GCM,data:iU689mGUQIxYRA8ByPHc6ET8U/MK+UTi+0rlebl6pBPFyWY25qpKi/KZWfCMLJtLnMLCcj6hPM7qKqi4fuXRNG9HpruVgzTDSiVfkUdUMN81XQOmFPd5xTIK4XbFTnyeoMpwODsncNRV+vHgXm3BO9FsbPIGizJnY/e3VB/bUeM=,iv:P29chsTWF14f1CqBWxcrfY4ORgW6s2aWXJ7mU0L9XvQ=,tag:nDLBRD0iYNzNPhKf/XpJGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
