apiVersion: v1
kind: Secret
metadata:
  name: gluetun-nordvpn
  namespace: media
  labels:
    app.kubernetes.io/name: gluetun-nordvpn
    app.kubernetes.io/instance: gluetun-nordvpn-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:vj6Op2/W0TqdNDUEYJDSyZsVYbnYQSf1,iv:nZteFK2GXPPAIbrkmcTwdl+6aHPxszp6v5e9mLi426c=,tag:PiE064P1ss3yXE61XhHgqA==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:U6Gh43Dk0Q2ha1e2SdgckwiAna/Wlr3H,iv:TG5JAVuyuwn3XY9dBYzLfitbMnxK2KMKONzFZ2Al1Wg=,tag:J5C0NGlP9ftHejO4gyuwdw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa1k1MTBmSzZWNGtHUG0w
        L2tWN3lqMlFPQml0aXlxamIrdW80bTZUL0NBCjAvV2Q0T2lTVGFCUVAzV2ovb2dJ
        TXl6eTMwRHlWOUFKaUVpOUZLaUhjUnMKLS0tIHA5YkcrNXlCWDFwUFlKSVVxODVM
        SVUvNzBmYk1zcFdjaE5sOGtYUU9GRDgK1RRLhP/7bFyW6yoB0+0Fz5VUjI/qo8WV
        NP+74u1O0t/hpnvgqfQR2+0wv8ubqFfsp9E0B6WU25cf8ZclC4JaEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T11:01:59Z"
  mac: ENC[AES256_GCM,data:EGCdMNfqQ+IdBAZSsxfBDWy8CGa8wxGrWihhOPo4YWAFalHiNrDyukHXyxCga0Is45/Oa3TNc+eqdadeH6R2LY7kb8WLQoskgaVOI/Uy1jjz2psY+A4nzUWM0DlYeC96GbEAr5gATU04orTzhHF3pjnlAjeAa++McJZXm5wYMD4=,iv:C8Gt1gULjy9BykDxcklfC2NKbVuorrixJcHYz5j39Uc=,tag:MV0i1pZ4bpJwQXMbKADdiw==,type:str]
  version: 3.13.3
