apiVersion: v1
kind: Secret
metadata:
  name: gluetun-openvpn
  namespace: media
type: Opaque
stringData:
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:784WIoszdAetqQ8sAAYGZVu2s+k=,iv:UrFWOQTbkRlw/wFPD89PXzQdMsLmlerX1v33iePJ/gE=,tag:STxFAerDfnqSmoBiDM1RGA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cC9GQ3J1ZURKMExsRXBW
        YmxQZTJXWjFkSlh4RzNqNnd3Nno5K2hlY0FrCjlZMytjS251b0lVdTRnTkk0eVJN
        MU93d3dneFVLUU80QUkwVGVBcHNTeWsKLS0tIERXTWNFL0w0VithZjIzcmdmV3RS
        Z08xZW5IL3F0M2FlMlRZaXZxcnQwcVUKeLzWXqIdU3gvRRQH6zysCTdOxPreear+
        kv6+P6xkaCzWTj13uhjBHy7PD3BBq2QSejYT5K68H7q7aWxY57yvDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T17:20:47Z"
  mac: ENC[AES256_GCM,data:tGyEmRvszmwbFzwMzfk5udNFtwrdOgNVZbtHzBzMzRN5cXnIkVUVs/6kVFS0HVKji46hSOO6HVl9m3EUQetEAkpJnS1SPAJj5M8uT8/Ym6Lmd45f38/mw1axLP6Izg3hPOaPg5EOeCsEPAb5A1uYpxgIfqMNUJO2m5WJJpJ24aU=,iv:g1nFWTqddyDvNh4AYQWKtYH8tF8MqSyTabJ6kR6wnUI=,tag:6TOtEeEBTNWZXNnj2Iyf9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
