apiVersion: v1
kind: Secret
metadata:
  name: gluetun-nordvpn
  namespace: media
  labels:
    app.kubernetes.io/name: gluetun-nordvpn
    app.kubernetes.io/instance: gluetun-nordvpn-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:8r8Gf9+zElq0VtQ40sqhvS6lurctig==,iv:d0NQCzhUtpZZ5ZCdG+GiGeTAJJFkFgzRHTEZvIDZHBI=,tag:ZJ8S2xPLyTpJrMnkaeyxag==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:cQAWGAs87si5caZl3dEUGn2fCKeGcTEo,iv:H8F015UNBGBKH+m5wWkELqkIcdMCHCgyymjzgj4FylI=,tag:Rh4o8RX9s6CFrJHmnTOoRQ==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWXpKRWdHOVltdFRRcHNl
        NHZJY1h2NW1haWRLSWhkdUVwVFE3T1l0ZmljClFneE9nOW9OUFhqaTN4eXdYVjNE
        SFU3TTZjK2VRbGkySFBJSTQrZHV3VTgKLS0tIHdWaFJkRzRpb21vUmZPS1Z3TEtp
        ZEhORXhEOG1WbkFsaTM1VmIzamtZMWsKi8N8SnmBtrzBh3BL3CL5s0TXgyZqTIWb
        BvRygbGgOrO/MFqwhc+e7SU6pHhr7aGv/V2zEP4ZLeW/dGdg+spKKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T19:48:48Z"
  mac: ENC[AES256_GCM,data:RcqmtOWHQnJyDiZV6JGo058LqWiwfX82pE8GWQDAKhdDoVIXARW1KHV2NS2CynzB4gn0/7/seeK7DdlGBx4fbNGKO1USNLWAOiw98rzHoUj5yFGpeL0TJb6N6IxSaEx9E6b//R7piMuxHd0DFl8UsMHO4tCVi/OgCFj7yHzkU/E=,iv:8iGz8g+UyakHJ2AMJ01oRRQMdJKh7Zw/uuMEVYCn/rY=,tag:yZpN/f/9R9GJd5rLdLbacg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
