apiVersion: v1
kind: Secret
metadata:
  name: gluetun-nordvpn
  namespace: media
  labels:
    app.kubernetes.io/name: gluetun-nordvpn
    app.kubernetes.io/instance: gluetun-nordvpn-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:34Qe/uSmCmhvuIoJn0IWaxpbyiUdktgi,iv:+5/X154ptFief3uGFdvfXjgKjhO8tXtAgh35UOJ8u8M=,tag:S1a94CZcFT5MfpQg0LtieQ==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:cQAWGAs87si5caZl3dEUGn2fCKeGcTEo,iv:H8F015UNBGBKH+m5wWkELqkIcdMCHCgyymjzgj4FylI=,tag:Rh4o8RX9s6CFrJHmnTOoRQ==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWXpKRWdHOVltdFRRcHNl
        NHZJY1h2NW1haWRLSWhkdUVwVFE3T1l0ZmljClFneE9nOW9OUFhqaTN4eXdYVjNE
        SFU3TTZjK2VRbGkySFBJSTQrZHV3VTgKLS0tIHdWaFJkRzRpb21vUmZPS1Z3TEtp
        ZEhORXhEOG1WbkFsaTM1VmIzamtZMWsKi8N8SnmBtrzBh3BL3CL5s0TXgyZqTIWb
        BvRygbGgOrO/MFqwhc+e7SU6pHhr7aGv/V2zEP4ZLeW/dGdg+spKKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T20:44:03Z"
  mac: ENC[AES256_GCM,data:X/NolCxsdh1v/IvlbxzpTMDsSttF6ZSWrBLw+g4ii+XgnIrW8gLIHUPv1ZDE3Yy9sq850cIy488B/XaxRasf6P7vGygSHSkS0jmD0hFt5Rc7dWavCsxte1UeAlswKP1rfv+r9kNxd9EXYgIOZF4EYlaBRe8j1SrY0LD/wMBAUD0=,iv:qIXzCQclQb/yOdxDq6oQ6v07Rill6MnUhPSmOXsK6dM=,tag:oLoQPq0fPes9cOTcwDGTRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
