apiVersion: ENC[AES256_GCM,data:asE=,iv:HPtUKj7Rp5Om3CqXZfI9iVKwdBFCuzJbHenEnH3vheI=,tag:PDTWfWMDWKsx81sdX/UJhg==,type:str]
kind: ENC[AES256_GCM,data:oC537Ruw,iv:l1EaYMfSGONtEYjtfS8fSZNg6vMIojvlekUza9Zmom8=,tag:PAaw6ZTZESNnaNzpv3a0FQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:AlBoawqVx8IQ/FLpDrPNWT0nc4AR2A==,iv:LE5MHUqO6yhBDPM5dEObYNgfVw9G6JtNpyRR4oykAOg=,tag:QnnfFmn6kCm7k+fdGQQKzA==,type:str]
  namespace: ENC[AES256_GCM,data:0IwkCxg=,iv:+nfAqa8EwZx/Zc7jBaPa/ZVJz4ePigi6w+GBTsiC5TE=,tag:jlaZ8llKtxn6uixite8C/w==,type:str]
  labels:
    app.kubernetes.io/name: ENC[AES256_GCM,data:tArQybrcRXNxhtX8dDFBZvy0h4J6fQ==,iv:TpKWAI7crBslXFzxRvpz0eyyFeLPu9khbyExIxS7b0M=,tag:SV44d+ZuF+yGFOeZeFdARg==,type:str]
    app.kubernetes.io/instance: ENC[AES256_GCM,data:SXnLj6F7Adq9YyR1n4Sv8uK55Qx7rnfOF63q,iv:Iy7jrgD1SzaSFeNFSyE7JsfEESgjH1nak4fW5wR9I90=,tag:FRnOXYMT1yKTkWvzHAje0Q==,type:str]
    app.kubernetes.io/part-of: ENC[AES256_GCM,data:Y3MCrioIbw==,iv:Bq6PgFQ+SjJl2fKLHS3sKSsvEpqe2hHI/NOo3++YkWo=,tag:/mnwmLm7Jp6wUTxy5hl0gA==,type:str]
    app.kubernetes.io/managed-by: ENC[AES256_GCM,data:IAfAMA==,iv:tYEgiOCdm4Zi4tzSwgSe7FGj96Wo8bL6UpSsIrZWcQU=,tag:1bgtxyh4ivEghq3btnzOAw==,type:str]
    exposure: ENC[AES256_GCM,data:7cTQ/OeZ4nA=,iv:Ou7HJg/WN33OZnJu8hMV6s0oCciSoG4xekZRU37Kqyg=,tag:zeC1/SclXWMlX63IUz+Tqw==,type:str]
type: ENC[AES256_GCM,data:mLpgDww/,iv:JKOaonJfv5t18eZ6kJ8drq4JvXM8dWlyg9zRQiNWvEs=,tag:R80z7btU/t8UZFJ1ApuHrg==,type:str]
stringData:
  config.json: ENC[AES256_GCM,data:RRsEcPVfzUvncMgeQXs2X9rJeXfIrXN08R+3t+Xg+lAUDXGblmpvin48lkAsiayg747lR55hD2AwTv3pfAGDjJl3v+vac94wMK4okX0Cie+sntxNy+sfNw4mdAeNNAPcY0QRw8mGkcaJmvz37E1VQ2pCSI3QWQ5V0DdvylJGmDo4FTnq5KChSxOaVisNKUKSYfgS5mFH4R530bmEfDUQyPJjczHbxDpy8WyiwsnnOTDZkfNJAniAftq5BIxYxNci0Dt7aKuNLqZtmaHBVS/AS3o81yjmdUjNzLyAZQiAoE/t9wJkkIFr36DGF6ihDqHT6wrjISBZX9y+y1jpMMlAVAi6fkkYLXRWdJceGfT5H4E+16neIdB2RrsDeuT1uWtZcjELnsUo3QzAghkVLsaJQaELeZJq10Eg95THhMHcer+nWMVxWKFP6bdmzan1RUOU85RJBLL/yb5rNygFGEgbdS+Hh+kopziMic011dFv9XLef/Ul1e6wBfI8CFYaedMpniFhDNif0c6OBoM1da4kUEUwXBcvfkMxkAMdiesAdPup+Tu1/ojzbLAoiBEcZZV7k8G3yEXyyvuOg+/VLSwxhMqjsKNxc4yuc8+ASF2+XdYZc7IySQh5gMZCAIQBqT8ohZou0g0tKfwMtChEEkvLBQTT30UHcrD0fvOCrX8DVEtdf6eQHhzYc8Mb9WqpP03bZ8W/mzk8uTXr5SQqTQ==,iv:3ECKkELEFvZwGkeXOt1/5fHCyUneVvHzu0NwI4ALB/8=,tag:8QxSdpebJPK2Alr3mzAdog==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UkdXTlNPYkllVGh1NkRH
        bWdrQWFkOWZETWhwbnBHbmhDWXJLdlhsLzFrCnMxV2lHS1lTajJaanFyQkxlT1ZP
        VlRBaTVWLzBrYTlsVGR6cmh4Zk5jb0kKLS0tIFpUVHVGZUJBVnJSMmo2a3kyeUR0
        TUVDaUp4eWNUdFVDRnhPUnNiRDBObG8Kd9k40NmoYG9YQ7DTbs63uhwEkBg0e4ya
        X73dNT84Or/bFpiCR5IAIby62r18DqGcRyopvPmWBXVTw1T1Cd5R7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T18:53:02Z"
  mac: ENC[AES256_GCM,data:q15z49XZetv857rxA524vPNBFo79peXRfxUYkKVjvL45wr7ue5F5Jy9AtvQ1TZ5Q8QU3QEudDopB1NR2H7ogP09bA0VJ3vpVsV3fdbWa9sx4nbsfc9RNx5M+B5rqhKCHDvP17dc1AbNAh636hhflSOw6Nq1mA2z5+4fQd7YE0S8=,iv:WbTyboXE7twLg0Bhq+rq6DiBJjbl0Fr7qsHJroXjhuo=,tag:eSWiO5Kl7p/J05i8BNGnCg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
