apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: searxng-allow-openwebui
  namespace: media
  labels:
    app.kubernetes.io/name: searxng-allow-openwebui
    app.kubernetes.io/instance: searxng-allow-openwebui-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: media-vpn
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: general
          podSelector:
            matchLabels:
              app.kubernetes.io/name: openwebui
      ports:
        - protocol: TCP
          port: 8080
