apiVersion: v1
kind: Service
metadata:
  name: slskd
  labels:
    app.kubernetes.io/name: slskd
    app.kubernetes.io/instance: slskd-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  selector:
    app.kubernetes.io/name: media-vpn
  ports:
    - name: http
      port: 5030
      targetPort: 5030
      protocol: TCP
  type: ClusterIP
