apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:woiUkbzLPJ2wW5bq2yvQ1ZobFdz4QN+BmOVls1QnrDYandSttCaUJHpbk+kTyudKbM+LzlDtKG9Yat0MGjL5/FhiWydhKKjUa/Ot519MTZ1lAUW4qZdoIBxEGg7MQ+fC5jEFecRi2+pBbByc7RhF2qpSiV6xXiaobWt8/d2cm9xoWhjA5YMJhRBX+zCIkcEA5xpegTXE2lANKe+dZzq01wHjSvMT2KQSBLo/VR7ji5Akj2Dah95lo3n7ljwS8zNfj4excIO7qcwGAhLFvEQwikaHkfXWB51HB+PHRCnQR3pfwzWmRuCPCe2DJ+BdDoMDu7zL8p7BV/2LUrNx14MLoA==,iv:pAvrU/TmLtHf5denZn2wygSP/ZfqVZ55ZSnChhCZDiU=,tag:4JbEUwF1kQ7ejy1kolq9Ww==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-read
  namespace: general
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZjdCeFFJRnBsM3N1NXlt
        ZmhudmZXNnFxeFJUSml3bmYwWGd6SzNobHlRCmY1RGdHaUp6N2dXWEp5a01VVDNa
        UmhJZmFqcGRqUHZkWjNYc29WeWRDUzQKLS0tIElwUUZlYUlGM0lrYTkrMmVoZ3l2
        WG14S3laU2RzNk9tTHlBQjFROEhva2MKZQNna0sf7G4BAY9qAApZ4T/s7X+PCWYU
        1VQ2S4V+zTt/2Fs5NZDZMJURH0Ol4JV0DiHHuITq+Qpyw/1U61KXmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:17:01Z"
  mac: ENC[AES256_GCM,data:SYHTn5JwAyjuDFNOjoy3dze1zl6VHqzqvpcGYx9ThlvYFm0l57CSUoNE1p3ZitHiYSn29wf9RS4/ich5scF7CUmFHMeslvUha0DHUEC1ugYxt4idBXhCT9ONaHJURM0+PuQoqihXBrGD8pPkb6P4zhFvnmNCJ8Sq6SKdgQvVYrM=,iv:oPJpV5cOiqp4Bo7yFyMPd5xohh1zkuPgrNr4g+0o1M0=,tag:VpH5MW0FEx1KUyxidO+2Pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
