apiVersion: ENC[AES256_GCM,data:5Ik=,iv:eMNc/NeBgJyIbaI1YEeH5bPLEV+Y1nWvi4xQhsE1iZE=,tag:UDMetzLr9EWf1cEdmtTLXQ==,type:str]
kind: ENC[AES256_GCM,data:JnzvtPZm,iv:MHpy973wSF0a7pXIIIVLqm59GlaTJx2EiNZ67wWEpJk=,tag:biZyqJfoQ9EIfPQnzkPSBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OM5JTqPycjlny2V5NIah,iv:/qGPbHKiXuQxvfGXx3krttmS5Gm+1tzTDy1carY/UAI=,tag:K5VnUK04OIpIfB7Ou7MaqQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:T2SDM1e4ZW7gu5USVFKs,iv:RfJynH+Psd87fYpIRVw8+gsTPUSsIvhiw2XVghwX41A=,tag:90h65PdykEbsBEPWc4Xnrw==,type:str]
        app.kubernetes.io/instance: ENC[AES256_GCM,data:ew9yeRCa2k7XyDEpE4GWHMiWDAM=,iv:TOUuDV460u0Rc6XMWf4+0dVynKoMmZ17LtZ1JsvD1yc=,tag:2Ja+HlbQMvVyRs4d0oG1NA==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:NSYmdYOEyg==,iv:g713BPdquGEwQZP29QEOXtSqfuoIyVymns4sGlGhBZ0=,tag:PzmdtbrVeyuW+UNMU3Vb6g==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:fAzYtg==,iv:g8RQ+1QOz45TwKo9BJa6b93wouLeYKRCAua1CgrTEjQ=,tag:wbv/okNVAvtgxao1xNedyA==,type:str]
        exposure: ENC[AES256_GCM,data:v75oTrL95SI=,iv:+FttjQnESWEbRr8aMHjl7DqNGacBrEnWlRD8k+2m4Jo=,tag:tEhv66ErFNeM87tiKK7ShA==,type:str]
type: ENC[AES256_GCM,data:jIOt7znn,iv:/PdN9d3mry2V2L2xjIBsMxuPy7KxYf5bV+i2dnHn99I=,tag:Kr16tLj+iv8NLUM5ewYJeg==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:zbqNZLRXHXjHmJOYCNAQNMWZbnhy55+zEAro/A8gfs4=,iv:o6kZthsQtBFbA+Rt1Z6+tOKQE4Qu0a648RhWdHHcCz8=,tag:SyB9CE7whC3bhJou7tqoOw==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:KcCkw2gS2BGNMCC3W+7yCFSZNtrZwHpsxbtF2BuP93obxpdRlO4UNrGPq4ky2j4FNu6dFa3/L0hrdt2gVk2llw==,iv:9yRYZvxZ1I08Uppz7Y0JDNF6yjSEJO/wThjINcbaQT4=,tag:/90Ux2hh5n+5Nb69jJZqsw==,type:str]
    OAUTH2_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:C14f18kdhCUno7+hAxwDxS2BuucTFN33RXILX0HGSMJZKk/4IRWv3A==,iv:pRq2xIPcnD4z2+oREUQyoz6sSqo8CcRh7m7OAzlcgvw=,tag:i/AHGFj7iVhVS9NTD58I0Q==,type:str]
    OAUTH2_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:zRVeItOTXFJqdcvXxt9H6YjyK+3b5ZOrmtbrZryPSsnihrGDIzA6nsm5xpLG98EltWZysX4wFDPWtc9P0Flu8UhVP+GO3hi5K1wDYkcBDAqsTLaM50JGMUc3jZllg8pWJlU5nOuW9oiM7MfOM+4PQMo5UEvKzInShMmu0nlpAs4=,iv:uSyRIXrXksNVn9W/R5ur1WrEJD9OsK2uA5oEA+3Ae/U=,tag:j8WfUWiyvOkS4k8bxy053g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZC9mVStxQkw0YUswNXlJ
            ckl0eUQxTnliNW5yK1l2UVVuVERhaTljcnhnCklsK1lSQW9QTzBmRmd4VUFUYXNm
            T2RtMzJzOXVhMUJOQkJkWUphSXJCaDAKLS0tIGJlMkUvK0gxN2hDd3lxZkhYQmlH
            L3FYOXB1alVuS0dXL3Nkd1M0OFI2aUEKsvDTqJyENLJX9KVzSWmYabbApWWgyQDC
            IpePcrAbpI3+/+Tw09nEgDQHKKC3JfCGLNg/HQLC/LTJQY3foMK5dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
    lastmodified: "2026-09-27T23:00:38Z"
    mac: ENC[AES256_GCM,data:UE72nOLEGeIAThcqfsk4tg21YB+ZgeIz+dQABxc1qdVrbPiMcWmHdsHt4bHTMBQZGD5fq3jsLqkuM4nxohGrRks6fH8N8bL8wUPJtO3oC0P/74yWTs9l7odCTG9gQk12SRQol2XSA7YFOKy8BQK+PPgarb2TOAU0l0vQaK0tjmg=,iv:bKx50R3CDajxUlxYkTG2iM46aR9a8YxJDAMb6UUPC/s=,tag:9oC47k4PnOAeKdSnYa0vyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
