apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    labels:
        app.kubernetes.io/name: forgejo-secrets
        app.kubernetes.io/instance: forgejo-secrets-prod
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: flux
        exposure: internal
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:dL/MlGpQJ748mrT55jqbOEiJDxyhYykbIeBX+vvtlJA=,iv:gmMXFVO6XwGMVHiPWpHNoFuky9uA6Vvgdioubi8cTjs=,tag:AhsE5RSJzHiyZ4nSbWJx9w==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:P3YaTvxljTYcWoZOTrgg21movOIcvPxfaT7/zG2aw0OTXHrPQqDI6rawJ6F6PIAY35lOYK2wm8n6S7dS8Z7+AA==,iv:JEMGyTxNLFOu/jW1YfOBDrSj89+4f/wE2MJFKKxEuNI=,tag:AYpIEFyspEU0jHdGUbDYOw==,type:str]
    OAUTH2_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:pNkzRygLoHpUzQuWk3VG+MMy0HxfUtGuFA86XqsflasJ6fWNPSCLlw==,iv:5amgDdn+xNUDj9Z3tONXMrnzLohALT21AfCN6Oi8+PQ=,tag:sDhTkc+4Mf6PIUCHlKiYjg==,type:str]
    OAUTH2_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:HWPhnGCRCW0o3i59eC7ePvSWqQBMeOagfENEVufFCmZm8u56J/JkemLHNavHrcneMCNEmUeWRRBx7o92izm56/0qx49xA5Qvo2WIt0F1vwiek6K7OsyMmoJvHic+34g5i1WPIv167aDttwH3EVOEQfAdC8wFxJrFsyvLLmMrSd0=,iv:RlgVUOVL7muAr2u83tFozdOZDmZ6sL3lV6I8FDr3pnc=,tag:SZf/6ksY58y6PHGlR/r0Pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYVo4UlhGK2tMaGVlNVJH
            R0w4aHVNK1ZCSGcvYlQ2RzMzQ2E4NEVuZEJ3ClN5UEFPeEdpazVZQXFFQTRPTThB
            RVZJb2xNUzJTTlgzSVRwZCtWYktjWVkKLS0tIEpLaERsWFFpQjdWWitvTTUrSE5w
            YXF6aCtjTjNuL3o0dTJZd3Z1YWYrczgK63OEoyA5nra8qT5zBpJngnTwxeauheed
            62cVGknKkCkhVYreTp/QHXFUv05E+405IttoRR17UF6Tf+dJo8kjWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T23:14:14Z"
    mac: ENC[AES256_GCM,data:sNWka6rjwtxGxkSlXX9FjB/y+Shn3B45ljEfoboURhIR3TzjBI9MybHOPB/t7NYC622WFz4kHQIlJS7UIlmh4pPVrDdLV5WNTN82WWjcsGL7+s6lfhdu/muyOwKwVAyvLyWVBL8N2wnbnVSEmu5on9+bQ3Uh+X9SPZ2nDHoTnWc=,iv:CYmh851/A/9oQ2U6ce+8rOZtgoDMFwviMKieHhTnSrw=,tag:2Fj9+HGRU9wZrR1rDY+1iw==,type:str]
    version: 3.13.3
