apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-postgres-data
  labels:
    app.kubernetes.io/name: forgejo-postgres-data
    app.kubernetes.io/instance: forgejo-postgres-data-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
