apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    labels:
        app.kubernetes.io/name: forgejo-secrets
        app.kubernetes.io/instance: forgejo-secrets-prod
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: flux
        exposure: internal
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Cz6whkO/qjZ/8Ilj2iJnhS72J6uZalgEp+f87t0nxmw=,iv:DWXvrWWkfm8H/URxO1Hmwzl1SxFWIjazhIgJojRGCh0=,tag:QwM2B1wzlf0bATpablQ0Pw==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:zgazMq/X9DOCIE6I+740Cw43K7AJlllaXlbon/cRkG32KTtVbspomGTf/j41pMw9h3EJk2Hcm4iHmAWwF5V/mA==,iv:mDeBjJhVBGKlz4oEsv3pwpGI0pe0ZGH59StrUb1hZ8A=,tag:1PLB44ZhvutVn5szLE/Thg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVzZXWWtjOTJwdExIQ3Fy
            QWx0TjJIek5hZ3NRMEtrak1vV3M2dnpLK2xzCi84ZU1YMDhFc0ZQaEZtMXB4Y3Fq
            T2lOV1dRVURjTk5zR0kvajR4RUErbDgKLS0tIHNpSGhZbDRQSVpodlhUaVZScTVn
            VHl2T3ZKemxRQ0Jzcmd1MGlPeThBUTQKn6Xf2mNz+KbFtcxtsdjCqGT2DfmYfYXC
            Tz6p84jH9LZ/ObBQaBWDEeac7i4JP7iXsQny4rvMxjehnfyYnge31g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T10:57:09Z"
    mac: ENC[AES256_GCM,data:1ClOiDttuMsgDPeeg6al9ZZT1w7gYrSbKtt25oGFvXrqLyRnWZeCW6nJTR3YMyaQopWkZtsAbd1MoTOi5RcDqRt8/qIr7J5WztHBdxafFjO6n5QCLa+W8XfKob5xoppOctjRdi5Kj4tC4/vjaz7u73kaf3XbNh1sDkT2TxhAtV8=,iv:F1krvjFxP0j3P0gPysLtWJ3N0GxKqsd7hN3Zs2R3WhA=,tag:82Zaikje/xXIsMvXCmg4kQ==,type:str]
    version: 3.13.3
