apiVersion: v1
kind: Secret
metadata:
  name: heimdall-hello-sync-s3
  namespace: general
  labels:
    app.kubernetes.io/name: heimdall-hello-sync-s3
    app.kubernetes.io/instance: heimdall-hello-sync-s3-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  access_key_id: ENC[AES256_GCM,data:DfafUCDPGwHDrg1jzH3GdOcsa4CvaRUpzxw=,iv:xVkVsEzM2EOnJgs/sWnGB8OQDVR+J4aVoP0HYtgDXI0=,tag:TchM1wMool8iEiYHUftPEg==,type:str]
  secret_access_key: ENC[AES256_GCM,data:jHe55TY796+cqNvfE7Vk5On/440hm3FKuYxHtgRvEkDLYVghwRG957VgBK9AtX3NOiWmLtdGif3Yf0udNLbqCg==,iv:hQrx27InnR5OVBD1eSqP9UtheDQCg55IJcuf5Y1345I=,tag:1ud3cAd/XhzzrKcY6R+bzg==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WnNtWXdMcFpUQ3N1SThP
        WVoxelMyTFMxKzJQUGYxSDQxSVdybXpLeG5vClN5R2liTTV3Z1JDdFhncWhNWTI0
        TExVandsM2JVbUNRMG1NTDUxNlA0Rk0KLS0tIGIxNVdFRFpvMERlUTlXaFlFSnBU
        eVVqbWtKeXY2ZUFWSFJwa1VOcy83aTQKznKn7n3/SGWmPtfKoq/naDyi+mK58xWL
        DsgxGkOZAqEWyKFonRgDwLFJH7BN769Ei2etaFNiylfJ+wRL7nUPqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:19:08Z"
  mac: ENC[AES256_GCM,data:OgMfGz2wXlC58nBYyXMLFb3M3in55UJcw1p1mnPbIPOnLHOW5Q9WqyYenQdNCcqoq/hoUOhmUlQ/jRgk7Y6SJknVmGopWgbugSlrw8dcnXVt3R2fN1hofQtcMw22zQMLHDN6EslnSEpXfpOZBdw8EQ9i2MQNq07dU343mzZq5jw=,iv:XcUojkkTrJLUo9B2dtg+VYlKRTst+MTnoC2BQwwibMc=,tag:AoMS4DwnKmSPeSUKjkm3ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
