apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: general
resources:
  - namespace.yaml
  - dockerhub-read.sops.yaml
  - default-serviceaccount.yaml
  - config-pvcs.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
  - homebox-deployment.yaml
  - homebox-service.yaml
  - homebox-ingress.yaml
  - mealie-pvc.yaml
  - mealie-secrets.sops.yaml
  - mealie-deployment.yaml
  - mealie-service.yaml
  - mealie-ingress.yaml
  - miniflux-secrets.sops.yaml
  - miniflux-postgres-pvc.yaml
  - miniflux-postgres.yaml
  - miniflux-deployment.yaml
  - miniflux-service.yaml
  - miniflux-ingress.yaml
  - openwebui-bootstrap-config.yaml
  - openwebui-mcp.sops.yaml
  - openwebui-pvc.yaml
  - openwebui-deployment.yaml
  - openwebui-service.yaml
  - openwebui-ingress.yaml
  - forgejo-postgres-data-pvc.yaml
  - forgejo-postgres.yaml
  - forgejo-data-pvc.yaml
  - forgejo-deployment.yaml
  - forgejo-service.yaml
  - forgejo-ingress.yaml
  - forgejo-ssh-ingressroute.yaml
  - forgejo-secrets.sops.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
