apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: general
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/instance: mealie-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
        app.kubernetes.io/instance: mealie-prod
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: flux
        exposure: public
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.12.0@sha256:8d962f611390a1cca667eed32a29e9467e9c01c523e2db3ad00f667372067f9d
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: BASE_URL
              value: "https://recepten.romanpeters.nl"
            - name: ALLOW_SIGNUP
              value: "false"
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_PORT
            - name: SMTP_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_FROM_NAME
            - name: SMTP_AUTH_STRATEGY
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_AUTH_STRATEGY
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_FROM_EMAIL
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: SMTP_PASSWORD
            - name: OIDC_AUTH_ENABLED
              value: "true"
            - name: OIDC_SIGNUP_ENABLED
              value: "true"
            - name: OIDC_PROVIDER_NAME
              value: "authentik"
            - name: OIDC_AUTO_REDIRECT
              value: "false"
            - name: OIDC_SCOPES_OVERRIDE
              value: "openid profile email"
            - name: OIDC_USER_CLAIM
              value: "preferred_username"
            - name: OIDC_NAME_CLAIM
              value: "name"
            - name: OIDC_GROUPS_CLAIM
              value: "groups"
            - name: OIDC_CONFIGURATION_URL
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: OIDC_CONFIGURATION_URL
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: OIDC_CLIENT_SECRET
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-data
