apiVersion: v1
kind: Secret
metadata:
  name: mealie-secrets
  namespace: general
  labels:
    app.kubernetes.io/name: mealie-secrets
    app.kubernetes.io/instance: mealie-secrets-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:gVIFK7QozTbgfyOV,iv:uUVMHnFZv6V93oDV/pwFffEGEOsLhRed+dqyEMdWMR4=,tag:j7DfXKP0OLIbmRpdtXjyug==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:VbvC,iv:dNQpPBBtbmho5cG36ZCObNaXnPUSPkEQ9Tx2bCUAo4Q=,tag:MUlrnlXB6m+JNgcQT0jWpw==,type:str]
  SMTP_FROM_NAME: ENC[AES256_GCM,data:E/luxYwn,iv:t8fi2O0FH5716SrmST6FE99MUdy9qOdSEcF7gsv1oco=,tag:iigNGGll9BtiXO8ZJAWgFw==,type:str]
  SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:K9Lm,iv:oTCYBkEqI9Y1p2SUFTITOXt3mgEQczHosTbs51DQe2I=,tag:2VSFilgSYOHjKx0ktbs4MQ==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:8hlpt+h6egOQS3n8/8H99/f5IvgsClWVwg==,iv:B0JUoDGGjNql/o2fTXSGMPWNRxtw7txq1W5iRMcl8+8=,tag:bfhdfwNM3NuJoBTrGV7oig==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:GOOHS3IgHqpiAWg9rbHUhSDJOjjhJJ4xdw==,iv:a+ECXIqqaA9MefPLGVDhBJWr5uw370Y6O45fVCMcf3Y=,tag:74rLwdmo8WiP9zid8LzIZQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:lHosrsgcjml3mxpD4Dxe5opS+k4=,iv:TLRXzwYMjd1wnOF0AkpZT9GIHN/XxTJ60MfUkv2geqQ=,tag:R/vz7H+9xOomHN1bwGvKHg==,type:str]
  OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:JE61kgfnO9QyJWbxI1YmwqAj+FSSU0OdoeMbegSDY2EN+6ePHUlIsbvr3sxyoC3alGPf3V/VNgtuA5IIBuacqzD5ICAbNy3qff+w3Yms5KI9,iv:OJop2xnPtcnY+5SqYdTNANRKA6E6+AehbfwPid2HyUs=,tag:xm7hAl1ImT7GCOFEXQmUlA==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:H2aJq3hSKnOlOeedt4QbwwFn/FoDgDlAfvHemHAbdC+Tal0JPSWVZw==,iv:+oBrcoKfq7H9rBXOfsRLf4djVzR4nDsj3xz3u4hu6GU=,tag:YkhRkCG8FlXI0t1PmM5suA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:T9Hc+/N5KdUmiZdXJkQu1VQ+fdba/v7vmUKlSUwKbC5AhQ5KwuUJpRmQRG3qQD2GJ+LHdMEZmmqkta5Zh4V8vOB9YHBRnLoaQSvqplNe8yeuSBEe1H6AmDlb8xDdYzGQN51PudEcI9o5f4JOTFdPuPw5GRHTbXIIlfcNvYsLZWg=,iv:PQuhUhy9Q0gawL9OSwc8tIbWIPr4cn3sEyb/4C6J4Aw=,tag:Il94lM5F+SIcRorSNIItmA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRVdHTFZzVVlFUk1tWkFl
        UzN5TnZVdldWcFlaTU8xUlZsaGJuWEpuM1M4Ck1TaTY5WUk3NFVxTTY4SGw4OWRK
        YmlRcE5QVjhYektWQUxpdVN5em9yN28KLS0tIE5RUHhLTjN5L2xCbTBQMGk0WGR3
        dVFKL2tBOUFVRlBHRDJLVGwzSkpQdVkKyHakolU5Y1JyPWScO9qiQpJWB17jjTDD
        k4mGVVCZLZO64urHLgjphjJ0b1U+Ec/4LygUBav7yw0FCOhJyGDMWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:57:18Z"
  mac: ENC[AES256_GCM,data:TgGWKUlH3XiQWqfgE24WLAPwInQoccbFvWq3+N3rC3dJdrZQTxqJoLL0D30umiV2FZtNUQMw38vxi3aGk/BQ9orClmVtIzBDmsL8y9qMM4U8zec9nbDKX/uH5tVQUzZTm8ym+dZbydLUiR+RL+eSf3FJ2lDOBebw7a0TTaW1/Gw=,iv:lQpMmzluIklCfMn80BJjpIy9QP3kkkOKv5lW+PeHkac=,tag:7RUhgtztw4LNnRP6sKUddg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
