apiVersion: v1
kind: Secret
metadata:
  name: mealie-secrets
  namespace: general
  labels:
    app.kubernetes.io/name: mealie-secrets
    app.kubernetes.io/instance: mealie-secrets-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:ZrdBVqZznMxj72qk,iv:smL+wGSkhTZDNQjzU2KLZvMsycVfzLXQMmotLMojKkI=,tag:hO6Ce6sIC3lYgqUzz7YVXA==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:rEFp,iv:2ms9p27KCZWcpddVnO9PRRMcUx7mHgZqW1lWU1U8HN8=,tag:Dc5t5ixJwh0FYjUPygtdMg==,type:str]
  SMTP_FROM_NAME: ENC[AES256_GCM,data:aggdK90H,iv:+mI7kFxnCEwVw8J3bW+c63gcQc5TPozlgXu1JZwQlkY=,tag:4JtZjc53v4LvFWZkieqdQA==,type:str]
  SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:ATdt,iv:H7X/DHQ8Y3PFQXHJomSf84RhqW9Fxihi4inT0+5hf18=,tag:Q8hWXJPrvuUQ5WTZu6UrUA==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:DugoHf6K/sxqQVBj+eluBjJGd3VFuNbZBw==,iv:o+Od0SzfHxneWBaLK55py2rSumhyi3vLyTG//7WT+nY=,tag:ZOsDdYHyMjhYy/arZNQEHw==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:ivH4hiOJLlbstpzfcQlw2Yk7ZBe7a2MyiQ==,iv:XZptnAwwcHUwiDna3gaNedTjEGwCn3ob3XBMDnJkGVI=,tag:SvpdMiz3k29NdKRFGwX8qQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:jO+lwDCwfGXtiVPfAtbnwzxvMtE=,iv:TLGl0sWaE+RadDwkJIoMfEZRkaMoW1KNmOAzIGnbDQI=,tag:qXTukd3PTSFmYK0OBhl5fg==,type:str]
  OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:GxblnPc9CwGiNlX4aiJtjuxG8+aSeamyVcHm+/VAglijbJ0lSWI2j2tWU+IYlSmz3IwS4ALVeErOBEFJorJwfs1r+fHRasrbL6MlOu0ZHABB,iv:GvVBdJCB5TGktIfbOuqYQalJhARd1KIPxIfPMBvMLQU=,tag:Gi6hcAUmZjTs5l4jM1H7UA==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:eurSTZ7gocNhdg==,iv:Kbnhcpf5+Rp4Nm39os94Z3VMInYEzI0ZxGIsQ8YOoNo=,tag:wjVIdxiTer3/FaX7+uZLnQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:F1Qqnx4zaX77aQ==,iv:TXdCf+rWEwxUio7yVoeOitoiW8Fj53+E3CgsYC/JDKU=,tag:Jpu2HkylF/nZC5IMZA8NCg==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZk9LZ21VRHRjNkUrazVh
        K3Y2NG1nNkZ3WVcvU2lKSnFmQUZGR1hTSWw0CndoRFZWT1ZSK205ZmpQbTFCeWVX
        bVRRSXVqa3Vnemc5cGg3Q1hZekZFVW8KLS0tIGFBa2g1ODFmRSs5ZHU5RmtRRXRq
        MWJYNVFzM01WZGJUNVgvTnBXS3dzUWcKMp3Iiy4sbjG9O8rvfsxK8c59swEHlmio
        hDyR6+1NoWhqcv8s/d5WvPfueqSCYWYI1tYKDQJ4+tiPAPmI3lJ26A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:49:28Z"
  mac: ENC[AES256_GCM,data:FfoP9sLcsbUdGO8Tt+WK5aSqBqf3ZINVxVCHdu/rE9hbsbLnq3TfDv+W/RPys8GUs51SAyWHEo6Ja1g6CFAjnOdmyulJqq5wE5Fgds2RtrpA9Cdu8QGw7FQz7LSg87PrfOSQLVoE4pPzLUFnkOqpJRAg792Ep2hh1DC+Z9TBC1A=,iv:Y6rl/66cKYViMTd3YY3NKoHSkjvxGUSYz+PTl4FwY7U=,tag:EQk8wdN0jOCShhTTSdIoXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
