apiVersion: v1
kind: Secret
metadata:
  name: mealie-secrets
  namespace: general
  labels:
    app.kubernetes.io/name: mealie-secrets
    app.kubernetes.io/instance: mealie-secrets-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:eWa/CQMq4Sy+uBRr,iv:023nD0WAkk3roLEwAr+PXsnvfCxFggqDeaMMDovz1aQ=,tag:D55xTdLG06692/EON5J0bQ==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:MKv/,iv:CgC2vLLTnRGdCZo2fi8aAokQ9ikKu38ZINJrvJX+LrM=,tag:FW2T4I5GUTfoGZ3dN2jO1A==,type:str]
  SMTP_FROM_NAME: ENC[AES256_GCM,data:rNs+4loy,iv:EeSQz1SoJWxHQR+9vCgnEEmcywqw8Fsn2t2UlOEXVEU=,tag:c1mQWBEtaMpxUJpnICvKJQ==,type:str]
  SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:qqyE,iv:iCyQUbPfPoaRMen5LYQUb0H3bZQ14kuLD2RKa2KfYyo=,tag:w/0WaYzdXdMDasYueqtPyQ==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:bjt6lkIe92lT24KP4josApXJ/AW4TTi0sA==,iv:/CvI32P7bVM2bOHkJyUtMsE7jr0RbVAwwZgrh0ub9p8=,tag:nUFiM61gc7QQrYwtb1sIzA==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:sDbiV/jQXkjFdIDk7/AaW2XfTg2Ne11ufQ==,iv:lOe2ZnjkTQNd6DVWk4boPdtbGCLILMN+TQ2yN0xArj4=,tag:2bKle82uYsFRoLAdM4RW4Q==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:epu4+Z41hJJ20kCwQW8K/gEY1aQ=,iv:HbJ6p/BsYYn4yZ0jGCVqhbMm7DbJ2wYIMhVQmi8bEzo=,tag:y+QcXy5T8zqBoF5uA/0gGA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbjkrR3BXSTRBcm5FSTBr
        NFdpNXdyVU9STFFuS0MzVWhvM0FSTlJSelhvCjRKVFRjcURKY05RTzM1Uy9qaWdG
        ZVU4QjFJallkWWhUVXpod0pObFlvYTAKLS0tIHd5RWR3RlQ2VyswOS9YZksvVzhG
        MnJJZXh4RThodGtpYjB1cFNENkUxODgKjg+dL9ez9d04Zqelr+dnFDNZwqD5nPFu
        kxZ5x+4AjEHkEKSF+9nYeefpGr5F9yAdPKPAJYbRPIPEt+Fu2z/Ibw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:42:59Z"
  mac: ENC[AES256_GCM,data:0AJUkwRumKP5y4oG4M2R9nuiYl3070kpraSqm2QZ15Xt4Q6RyQqSkTGnZHKsGAZMuxzwEN32t3Ef1jLxpbGODiININ1gG7JcgxVDf2vQIvHH54ZS7o7/iy25E6IMX24Nq/A+2Pj/3in8SVcarj75tskIxAHYaUXUxYVLlSC+qO4=,iv:jLZyto/1kMczmAixWmT2Nfj4Y1WdYkMUC1QYTISmcMs=,tag:9hfWn90TyI0KXdxHFtIydw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
