apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secrets
  namespace: general
  labels:
    app.kubernetes.io/name: miniflux-secrets
    app.kubernetes.io/instance: miniflux-secrets-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:VF2sAUhGh/zBMmvnfbmludfnUNZuKUQFu1QXLhyhfIc=,iv:mO9OEGBNHE8AhNbwx7r2lTpjJfbdkDpt2KTSU5G3b5M=,tag:TKCR0OdlNY/RtlywD/3xfw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:tLUGp27ql4QZFdB/eV8drQtBE7tWEdz6Mm5Zvg+6GO3Lo8KLM08bZPcdkkviHRTO5vHht6WhT3Nba1gRVuBRkNKbewsQpTzgz7wAy5v1LQP1SkaUkxBNoXnMv5MnTiU+7Vg7jw==,iv:6uiLlqFZ0rBjnMsqodrm8xvEsKxazR/I6MlOqu80M6c=,tag:eqhH9rlWINQ+I7HGOSr/iQ==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:KY6gh1Hk8dNasEI=,iv:JGp3Npg1qp3HRMZThXRPtVSd7eZSQgYHD8DFUN+i77k=,tag:6w3ercWvlwopHncsLmRvMw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:aC7v92K3q7RozmsEPgKbsHgsGJAXOJNCFoznEg6Vd7I=,iv:FfZxqEj3O+rwoP4hb8fZ8zHWV9KSFU5mFO4w+dwt/TE=,tag:v4MNqeylgGg0j3ezpsH5+Q==,type:str]
  OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:h2j8Jc2cgYGOegUldANpcE5r7NR6TRqfmyIdswU5TmpTlnSCpBXIlA==,iv:VyPgzVfQNUPRswmAA+lFdjUasQEUIKKCGRGwD2pebKk=,tag:ZJHzJ5WOuXCNUENeGEf2fA==,type:str]
  OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:RDzebeDI1irXx0tlBT3uq0MYCbbtz0zz0F0QD/pOEdsjlhDPNNrZW26FkfMvikvLn6QTB4K6RMfQxnqdQdUIV2DlRN3RrcF1DnA0e7gEhwtdg/Mn1UMTl5F633noBLj7oyUuwGEO3yAc4okE5blev7ADAjUYJpEjpl9PJ3xcCco=,iv:/THAQm74jugYWic4bAILz4NrcWwcN90Xq+enrL/rCqk=,tag:7p1SbacGzPJSvYtU4RwPDA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQlJwdm90OTRRTGxCUk1M
        ZEVjbnBRRFFZMEZaY05nMm9ZWUp3UjdhK2c4Ckdod2JHcHlkQzZqUzJwWFhDS1g2
        cU8wQTNoN3JPUFlPakJrNDJFTkV2R1EKLS0tIHNiZGdENmh1Ny9ESFk1S1dLTW9I
        MkpIVkIzWUt3azNDQitXU1EzSWNhQTQKmYgoWBm9Y6RxDPjsANYGSxiv1gUMOGGF
        JFDViA0pjCXdkja+r6xMgghULAS8XpDepEff4nLf7oaDRvpvuc0Nnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T13:40:12Z"
  mac: ENC[AES256_GCM,data:KgoVt8RQPYBi0B4qhFSPyLltvaYuXrxevjtadbiboKSUnFNVI/1wl8KJdYW3p2pl7vssw7N7cFGD3ge7Zm61edTyvWMvguEGkR28txHhsduYGgco4xM3Ylrk5FuOahWYmxhkDOnU8WqyOX4R6gz/QD5pgYZOJ8d36plmuBtXaAw=,iv:DGTEVIqkj72jP9rXqIkoRHvzfGX3Wmf0Rm7GrZiJKXI=,tag:8Q4StKcKmR2KNhcnNMsPkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
