apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-postgres-data
  labels:
    app.kubernetes.io/name: miniflux-postgres-data
    app.kubernetes.io/instance: miniflux-postgres-data-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
