apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/instance: miniflux-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: miniflux
  template:
    metadata:
      labels:
        app.kubernetes.io/name: miniflux
        app.kubernetes.io/instance: miniflux-prod
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: flux
        exposure: public
    spec:
      containers:
        - name: miniflux
          image: miniflux/miniflux:2.2.19@sha256:8810dfe7f4d9979f9dc1385607695c116f049daa586c635a9a1fb3c58936b074
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:8080"
            - name: BASE_URL
              value: "https://rss.romanpeters.nl"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: DATABASE_URL
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: ADMIN_PASSWORD
            - name: OAUTH2_PROVIDER
              value: "oidc"
            - name: OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: OAUTH2_CLIENT_ID
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: OAUTH2_CLIENT_SECRET
            - name: OAUTH2_REDIRECT_URL
              value: "https://rss.romanpeters.nl/oauth2/oidc/callback"
            - name: OAUTH2_OIDC_DISCOVERY_ENDPOINT
              value: "https://auth.romanpeters.nl/application/o/miniflux/"
            - name: OAUTH2_USER_CREATION
              value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
