apiVersion: ENC[AES256_GCM,data:8yA=,iv:1XsrUCar8Y7PExW1A7FwlHcg/lTY/x3e9JEV9jpevfo=,tag:OlHh9lSpUnPMn8EhZZlUjQ==,type:str]
kind: ENC[AES256_GCM,data:B6+7UPAC,iv:ifKmRc7oGsjGmi5ROwPLkLbXO4pLVr2izuF9jxgoWIg=,tag:4udZH3w+2V1J23BLO8m3TA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:Q2emc0GTiXGt4PFX/Q==,iv:CsX/mldEgCTBnp/0i+e3/mvfqkXmnsQZFM0HqHK0aRk=,tag:1fOYb7imRE5SplbfWG9Pow==,type:str]
  namespace: ENC[AES256_GCM,data:sQRQFNbcvQ==,iv:0zwbVzEs36iyPokSujLaSLFziCQfIX/b4T3CmVyT6Ho=,tag:tMMjHyGizOBoC+tIOZWXMg==,type:str]
  labels:
    app.kubernetes.io/instance: ENC[AES256_GCM,data:zKt8rZrou3jXL5cehpF33YXF,iv:xYgTtXuq334wgTn3MhZVHbOfPgyN9eUlEYbC+i90QP4=,tag:Tk+KoT8yc6QPlnJovW6Y+g==,type:str]
    app.kubernetes.io/managed-by: ENC[AES256_GCM,data:GCVQ0g==,iv:C3TfZtA/renB6i+T/LHlXWXSomBJtgSpHkq9TrlPSS0=,tag:0fzqF6B15qqOZBtzDlpQmw==,type:str]
    app.kubernetes.io/name: ENC[AES256_GCM,data:6WQyDdE4q672RAx6Zg==,iv:PfTT6cI6kDwDt2YQ1NBY57zHIoiVqXN27oqZi68e+gw=,tag:Ieu0j7d82TcBZr7fKbEhDA==,type:str]
    app.kubernetes.io/part-of: ENC[AES256_GCM,data:ND1iGczBOQ==,iv:cgyHvVnj6q3vyG+gewz4nxr57EzQFQrGli8wl+8+0P8=,tag:rAnlIOCndKQbSF9y4jfSZA==,type:str]
    exposure: ENC[AES256_GCM,data:ArfOfzSQZEI=,iv:7LsRtGR0npHxvZb/Q3fzBL4lQYDkKy2R1eYmiaBykQg=,tag:4FcLoy6GRrplA/czFBvbqQ==,type:str]
type: ENC[AES256_GCM,data:z0QOPITY,iv:mgg1ibeWVN1E7eRQTt0pdtIZrYLqkgpa/0QdtEYRKXI=,tag:3SXK8cwglPk+NBExxQbOWQ==,type:str]
data:
  TOOL_SERVER_CONNECTIONS: ENC[AES256_GCM,data:xud3a4nI2QhCpmQS+GTEFVIxaPBH8egS6DZl/lOyk1A8FhQUwtYn0G1T24ojSp+TOHQZO59jkAt7LVs0c9OqRLc7Buk+Kz5rOJgdj1rh1I9WAMQQNkxBfg8rw744vCfPQFPwllyopAGmnUXcYZjl0lGdo45jpAzuZ8PtFoi02YIadQ8ubsWoPlObZGN+zLzgxrO6k4OVUXqUELZWoE08OPp33lqEWZzHKdg7oJPnYLbM6q/Dm+SL0XDxfzLKj7w+ARRLKnAfeszcVLlWbsg0sYhn2PG56BY1Aqv/sy99ej7KbzbTAczOT0jXnCvVJQhvcBI6LeTmUTIMztpNQyLujS/QqzxCFnoTWedxto0e+m8IOul7vWLS7QW6L5SgkmFPOr3FBBGSRjrSTEWD1+uCuyFggx7skwvqqVUz9emT3BWr3xLhX1rnZTJJeA1jblzu8ijXJSIEjhf25ft3nIBanbGn/DXbEbBbql8LBPvmljEWlpy56TR2uuhv1/QkHMS/brIm3khP4YeWRVOW78d3cQQh9nUYEseSqTOvN8ZhUOQf9KoQPYjcESE4mtbcsYE/o27Dg3d+VtksDAC6MB2fiRPx5JwRo3XH7xNm2rsWjltNjm3gF5L/Hi4aCieMXuwdmNYC3ttUGnua7ROFretoTc++SXWVwQIcvuc3Sfh+jz2YF+fRSBS4JssenLWcQeX6W68ItlmrnWQAAG6hvK5y4LE3cd942FEHV3aZ/v4zVfHTfP9E9yifI8dItpa7OczEQr4QaSq5Lb0nCvoZed+bqZgPUFlm6bnb1W9/mP0Bj/Tu9SEJqM558EM5BzNLXyNZDHRoyKkJ1NTuTcGjfwAts9xgslYXcrZxn+ANrA+1gJQ=,iv:L5Jbo8Lxgqg3qy8nHwvPC4Dpk/skx3xWDqbFECAMRVw=,tag:065MC5GEzk3o1czLtsXDIQ==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArenQ1NDc2K0hOa21ydGt6
        dTlIY3Q5VVVMSytndXZFSll2Q2lDVmtZK0hjCi9MRC84aFd4Uy9pZzlCUkw2QkNi
        eGVlWFZuZ3plR3lVNTN2bkZvVkhoNFEKLS0tIHVrbURWT2hIZUpOd1pqNWw5czBj
        cmwvU0NNVjlTalg2Kzk5K2QvTkNqSzgKCavRmKyPEMeV2dDZYLrrFvKxgUze3eYi
        GUMXu5WAjPFMFivVlk3ylb/tKTlKcbMPb9hLN1MJrQRa7wUABeyPnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:12:14Z"
  mac: ENC[AES256_GCM,data:STTh1hFd9UB6656Mz5Ti9BPTT8rOTwUU3Aq73PDlZs6rMjIyU0tYPclwahCW80GNyCQUDy2hyw5VP+DLbPsiIP+mZVqH28OZgc4MN10WIyptf7/cpCmsVY5uPrjv79mHFlc4TVcIr3RzSK9gR4L5P5AbMlhehDlptk9w2sQnbWM=,iv:xKtKdxF0JFlhunx0QAtZ1oF0/AlYGFluNJiEVKc+54Y=,tag:Zo1zUna4dtt9vturvU1zJg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
