apiVersion: v1
kind: Secret
metadata:
  name: openwebui-mcp
  namespace: general
  labels:
    app.kubernetes.io/instance: openwebui-mcp-prod
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: openwebui-mcp
    app.kubernetes.io/part-of: homelab
    exposure: internal
type: Opaque
data:
  TOOL_SERVER_CONNECTIONS: ENC[AES256_GCM,data:N6FmsORFR3+Di0epgSLNzSpndzFpCSdG/GESvsGM8NjHv/+u5lUqtX1H/JM5iaIoavPYNlJaBSFD8h1EV9ymPkCVpldsx57TuG5YuVTCRI7GyMlacZe0qeUG/jUarSUCysOUo68IFn0pXqvV8ac6PDrimoOxZgUlDh2vd1dLbCb2uYFaNCFjOQdutfABunROUGVkl7RiTOxQASYIc/ALp31OjSoTlHWmLA5YhanQyeIWGMM3TI8AVtTFsPyUG5xk32tehv2IT1I5cczrNeRIgfdttgfjVnUD68BtU9Vnj7bQcg4Zx0TYoJexpwY0kxalDYgOHaeWpGxZT6R8QgIuLVCf4KKs7yc2sIXBdU1SxXJcDvq4UuAXCSf1VtaPlnD6hKJOzw4LhaHNQ5aEeQ7OhWAEhD2O9tVnbrnU5nwzXpoEuczJPw828II2EksEiolu1WWRCwh08dc5lwh91znwRMkOzr4zu65IUvahvec7cogc7ut5aofE3ZmPXaCwfxyWJpixcsAX/disV/40rqxc5qvO1HRPbYIOmTqVtqkZ2vx5Ah81af+stU6WwYqPs3XVpJMZhsYnWH7D6OFxveyzMqBtoLpeX5e5fs6K3yWjdhQXtxUWfYFUeHv7bNZ9ahyEle+dVZBJ+QpcOjUJ6RuBKErLkAnMNrPMTHfw+9Hoq3kzxuxiJFJ77WGP727vByXiG0wK8dXknjMcdWQOYNLLqV9zSLkm+htLC2uKQyzy3Dt6sT/M2fROHrTSLlXa11oWQ4lOEU4MsTK7niqGJ1S0mcLHWEN190cTNUGbHtOx/v6zOLMmz1CIGdlTGbl6pNpN5gths2F2zCRLfLEKi09qJWskv6UqDNZDScaYIUYf0kY=,iv:PjEnqinh90aTVCs/AVkBUwByGm6CCsQe/t8/zMg8Thw=,tag:G5WAg1t/73zwItqa3RomPA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbzFBZDVLZjZpeDFmZCtJ
        RTFvNDZ0MUpNMG1ZNmJTc3ZJTVBOQ2R0MWhzClVyd3JLOURxQjZPazZYYzhPS1NO
        dkJHUjhnUmxaNzFjamtzMDdHWFd6U2MKLS0tIDJJMVBZK0hvTUxDMWtSQkhZaEZN
        WFZyNmZzanpHeUpJa0xsdnVTR0p1Sk0KdkNVLpwcfmelej3YR7ZxHeBPY1YD1+hy
        ACvoZFMgXty7FyDue85Vtct8DvVwMc4iLucHdRLs1ol9AKZXk7iukg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T13:17:01Z"
  mac: ENC[AES256_GCM,data:sOzN+9BcsiC8UBMwfZHKWgIP2IxMXvlTEJ6cMbStFL3FIMi7aTKRxj0Zt4laySvVsjpQ8Zf2IqD2WB7tlRXGF+/k3XxXn2w761OhCtef2G3y42kmRcux2aOEGHM4GcnH67oOqYjWnzOe+uVSZq9WqQbOTAIXOpBFEWBJ2lWXnXg=,iv:fmmFt270YGdwWtZ/hZrAXvrM+hy8F8c7DuTdMj7sHIw=,tag:Xrzs8zN+9FkhU4xNrd2iZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
