apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: infrastructure
type: Opaque
stringData:
    registration_token: ENC[AES256_GCM,data:g/qi0ADSEWpJGDcUlhffFP+N560uQrVsRBAqeau2T91ud4cTfPoGi24Q3A==,iv:h+CRrsr/2SLu2VMohtxo9+NNhx6Sc8D6eoU44uYKP0k=,tag:/L8gxbLpwPimv9GgZPyFvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZVA4YXR3a1pZelp5clhR
            NXUvY2pzai9zdm9nNzIwaFlaYTMzaUtnNndvCmNqZytCMWsvRTJYb2JaT2JFQjVB
            QUNoN0tOQmF1VmtIRXVTUkkySVViSmMKLS0tIFduUGNhUVdqOSs4N01Wb3duWUdR
            QjFlOGpseUlUMkIweURBbmJiZktYZ1kKg/eijvJeV1mFLmiJ636EiKkbCMzBXcF5
            Q5QEn3rEkg5lCb1CE0IOcDKjHiFvrhdUVHQnUjx5EjDMCgWTuGDagA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T15:07:30Z"
    mac: ENC[AES256_GCM,data:X9H6B0fmoHBCRBelLZGm7W//1PixL9aAZkm0GQx/ITKzduushEs7el/9bTmcCezYlBOb2Zc93zD9Smq0EAcC76BhzRG4FxKdMYww5QHngfPDBnUXbPqZgbhXbUVp3ivnpUVHp0J7YMRCeKfhlMpzi/W6Mlr6sxvENnryyadyxdM=,iv:XQPw1jpNcwxu95nKQNd+a5P0lHXdfz+2PR9ybfrtFLA=,tag:u8GrDFdPtTuEOC7jv8fp6Q==,type:str]
    version: 3.13.3
