apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: romanpeters-redirect-eskimos
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: romanpeters-redirect-eskimos
    app.kubernetes.io/instance: romanpeters-redirect-eskimos-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  redirectRegex:
    regex: ^https?://(www\.)?romanpeters\.nl/eskimos/?$
    replacement: https://code.romanpeters.nl/honden/eskimos
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: romanpeters-redirect-root
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: romanpeters-redirect-root
    app.kubernetes.io/instance: romanpeters-redirect-root-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  redirectRegex:
    regex: ^https?://(www\.)?romanpeters\.nl/(.*)
    replacement: https://hello.romanpeters.nl/$2
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: romanpeters-root-alias
  namespace: infrastructure
  annotations:
    external-dns: external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-pub
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-romanpeters-redirect-eskimos@kubernetescrd,infrastructure-romanpeters-redirect-root@kubernetescrd
  labels:
    app.kubernetes.io/name: romanpeters-root-alias
    app.kubernetes.io/instance: romanpeters-root-alias-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  ingressClassName: traefik
  tls:
    - secretName: romanpeters-nl-tls
      hosts:
        - romanpeters.nl
        - www.romanpeters.nl
  rules:
    - host: romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage
                port:
                  name: web
    - host: www.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage
                port:
                  name: web
